apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      stringParam:
        type: string
        default: defaultValueStringParam
        required: true
      choiceParam:
        type: choice
        options:
          - opt1default
          - opt2
        default: opt1default
        required: true
      booleanParam:
        type: boolean
        default: false
        required: true
      numberParam:
        type: number
        default: 1
        required: true
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "string Param is '\${{ inputs.stringParam}}'"
          echo "choice Param is '\${{ inputs.choiceParam}}'"
          echo "boolean Param is '\${{ inputs.booleanParam}}'"
          echo "numberParam is '\${{ inputs.numberParam}}'"