apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:
    

jobs:
  gitlab:
    steps:
      - name: Checkout4
        uses: cloudbees-io/checkout@v1
        id: checkout4
        with:
          provider: bitbucket
          repository: scm/qaas/python-hello-world
          token: ${{ secrets.BBDC_TOKEN }}
          bitbucket-server-url: https://bitbucket.saas-preprod.beescloud.com
        env:
          RUNNER_DEBUG: "1"
      - name: Commit4
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 4:"
          echo "Inputs:"
          echo "  provider: gitlab"
          echo "  repository: https://gitlab.com/rthomascb/actionman3"
          echo Repository URL = ${{ steps.checkout4.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout4.outputs.commit }}
          echo Commit URL = ${{ steps.checkout4.outputs.commit-url }}
          echo Ref = ${{ steps.checkout4.outputs.ref }}
  gitlab-ref:
    steps:
      - name: Checkout5
        uses: cloudbees-io/checkout@v1
        id: checkout
        with:
          provider: bitbucket
          repository: qaas/python-hello-world
          ref: v1.0.0
          token: ${{ secrets.BBDC_TOKEN }}
          bitbucket-server-url: https://bitbucket.saas-preprod.beescloud.com/scm
        env:
          RUNNER_DEBUG: "1"
      - name: Commit5
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 5:"
          echo "Inputs:"
          echo "  provider: gitlab"
          echo "  repository: https://gitlab.com/rthomascb/actionman3"
          echo Repository URL = ${{ steps.checkout.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout.outputs.commit }}
          echo Commit URL = ${{ steps.checkout.outputs.commit-url }}
          echo Ref = ${{ steps.checkout.outputs.ref }}
  gitlab-sha:
    steps:
      - name: Checkout6
        uses: cloudbees-io/checkout@v1
        id: checkout
        with:
          provider: bitbucket
          repository: qaas/python-hello-world
          ref: d19d4460d89a71cee9a21a386eb5b4fa0688809b
          token: ${{ secrets.BBDC_TOKEN }}
          bitbucket-server-url: https://bitbucket.saas-preprod.beescloud.com/scm
        env:
          RUNNER_DEBUG: "1"
      - name: Commit6
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 6:"
          echo "Inputs:"
          echo "  provider: gitlab"
          echo "  repository: https://gitlab.com/rthomascb/actionman3"
          echo Repository URL = ${{ steps.checkout.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout.outputs.commit }}
          echo Commit URL = ${{ steps.checkout.outputs.commit-url }}
          echo Ref = ${{ steps.checkout.outputs.ref }}       
  gitlab-branch:
    steps:
      - name: Checkout7
        uses: cloudbees-io/checkout@v1
        id: checkout
        with:
          provider: bitbucket
          repository: qaas/python-hello-world
          ref: new-branch
          token: ${{ secrets.BBDC_TOKEN }}
          bitbucket-server-url: https://bitbucket.saas-preprod.beescloud.com/scm
        env:
          RUNNER_DEBUG: "1"
      - name: Commit7
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 7:"
          echo "Inputs:"
          echo "  provider: gitlab"
          echo "  repository: https://gitlab.com/rthomascb/actionman3"
          echo Repository URL = ${{ steps.checkout.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout.outputs.commit }}
          echo Commit URL = ${{ steps.checkout.outputs.commit-url }}
          echo Ref = ${{ steps.checkout.outputs.ref }}

