
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publishAndDeployArtifact
on:
  workflow_dispatch:
jobs:
  publishArtifact:
    steps:
      - name: Register published artifact
        id: publishArtifact
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: testQaArtifactRegistration-26d62b3e-b59e-4a9b-b8a6-18009f3f5de3
          version: 1.0.0
          url: docker.io/MyTestApp/testQaArtifactRegistration-26d62b3e-b59e-4a9b-b8a6-18009f3f5de3:1.0.0
          digest: sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3121
  deployArtifact:
    environment: QA
    steps:
      - name: Register deployed artifact
        id: deployArtifact1
        uses: cloudbees-io/register-deployed-artifact@main
        with:
          name: testQaArtifactRegistration-26d62b3e-b59e-4a9b-b8a6-18009f3f5de3
          version: 1.0.0
          url: docker.io/MyTestApp/testQaArtifactRegistration-26d62b3e-b59e-4a9b-b8a6-18009f3f5de3:1.0.0
          digest: sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3121
    needs: publishArtifact